### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by raderio** [liquibase/liquibase-postgresql#2]
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.0.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">
    <changeSet id="1" author="a" failOnError="true" runInTransaction="true">
        <sql>
            CREATE OR REPLACE FUNCTION update_on_change()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = NOW();
                RETURN NEW;
            END;
            $$ language 'plpgsql';
        </sql>
    </changeSet>
</databaseChangeLog>
```

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_111]
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:597) ~[na:1.8.0_111]
        at java.lang.StringBuilder.append(StringBuilder.java:190) ~[na:1.8.0_111]
        at org.postgresql.core.Parser.parseSql(Parser.java:1020) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.Parser.replaceProcessing(Parser.java:972) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:309) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.QueryExecutorBase.createQuery(QueryExecutorBase.java:320) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgConnection.nativeSQL(PgConnection.java:703) ~[postgresql-9.4.1212.jar:9.4.1212]
        at com.zaxxer.hikari.pool.HikariProxyConnection.nativeSQL(HikariProxyConnection.java) ~[HikariCP-2.5.1.jar:na]
        at liquibase.database.jvm.JdbcConnection.nativeSQL(JdbcConnection.java:236) ~[liquibase-core-3.5.3.jar:na]
        at liquibase.change.AbstractSQLChange.generateStatements(AbstractSQLChange.java:218) ~[liquibase-core-3.5.3.jar:na]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1257) ~[liquibase-core-3.5.3.jar:na]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) ~[liquibase-core-3.5.3.jar:na]
```

**Comment by raderio** [comment]
I need to put procedure in **createProcedure** tag not in **sql**.
