### ISSUE TITLE
generateChangeLog - DatabaseException with liquibase.statement.core.GetViewDefinitionStatement

### ISSUE THREAD

**Issue by MarkWojciechowicz** [liquibase/liquibase-postgresql#3]
When running generateChangeLog against a postgres Database, the following error is encountered:

_Unexpected error running Liquibase: liquibase.exception.DatabaseException: Error getting <my db url> view with liquibase.statement.core.GetViewDefinitionStatement@<some numbers>_

**What is Probably Going on**
Using debug mode, I found that liquibase was trying to get the definition for a system view, "all_synonyms."  However, it fails to retrieve the definition because it is filtering on my user schema:

_select definition from pg_views where viewname='all_synonyms' AND schemaname='My Schema'_

This ultimately runs into the error: Caused by: liquibase.exception.DatabaseException: Empty result set, expected one row

I added this view to my schema and it subsequently failed on a different system view, "v$version."  I did this exercise for a while and it continued to fail trying to retrieve the definition for various new system views.  It appears that GetViewDefinitionStatement is iterating over all views, regardless of schema and that the target user schema needs to be filtered there.

**Details from the debug:**
liquibase --changeLogFile=changelog.initialize.xml --logLevel=DEBUG generateChangeLog
liquibase.bat : DEBUG 12/20/16 9:36 AM: liquibase: Connected to <mydb>
At line:1 char:1
+ & liquibase --changeLogFile=changelog.initialize.xml --logLevel=DEBUG generateCh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG 12/20/16 ...ntSchema=txpidv:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG 12/20/16 9:36 AM: liquibase: Setting auto commit to false from true
WARNING 12/20/16 9:36 AM: liquibase: EnterpriseDB jdbc:<mydb> does not store DATE columns. 
Auto-converts them to TIMESTAMPs. (edb_redwood_date=true)
DEBUG 12/20/16 9:36 AM: liquibase: Computed checksum for 1482244589438 as 24569be9b560c20ed0ebc723ff722c13
DEBUG 12/20/16 9:36 AM: liquibase: Executing QUERY database command: SELECT c.relname AS SEQUENCE_NAME FROM pg_class c join pg_namespace on c.relnamespace = pg_namespace.oid WHERE c.relkind='S' AND nspname = 'null' AND c.oid 
not in (select d.objid FROM pg_depend d where d.refobjsubid > 0)
DEBUG 12/20/16 9:36 AM: liquibase: Executing QUERY database command: select definition from pg_views where viewname='all_synonyms' AND schemaname='My Schema'
Unexpected error running Liquibase: liquibase.exception.DatabaseException: Error getting 
jdbc:<mydb> view with liquibase.statement.core.GetViewDefinitionStatement@729d991e
SEVERE 12/20/16 9:36 AM: liquibase: liquibase.exception.DatabaseException: Error getting 
jdbc:<mydb> view with liquibase.statement.core.GetViewDefinitionStatement@729d991e
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: Error getting 
jdbc:<mydb> view with liquibase.statement.core.GetViewDefinitionStatement@729d991e
    at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:265)
    at liquibase.integration.commandline.Main.doMigration(Main.java:1011)
    at liquibase.integration.commandline.Main.run(Main.java:188)
    at liquibase.integration.commandline.Main.main(Main.java:103)
Caused by: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: Error getting 
jdbc:<mydb> view with liquibase.statement.core.GetViewDefinitionStatement@729d991e
    at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
    at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:263)
    ... 3 more
Caused by: liquibase.exception.DatabaseException: Error getting jdbc:<mydb> view with 
liquibase.statement.core.GetViewDefinitionStatement@729d991e
    at liquibase.snapshot.jvm.ViewSnapshotGenerator.snapshotObject(ViewSnapshotGenerator.java:103)
    at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:60)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
    at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
    at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
    at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:246)
    at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:363)
    at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:385)
    at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:293)
    at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:267)
    at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:80)
    at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:53)
    at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:28)
    at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:150)
    at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:139)
    at liquibase.command.DiffCommand.createReferenceSnapshot(DiffCommand.java:219)
    at liquibase.command.DiffCommand.createDiffResult(DiffCommand.java:141)
    at liquibase.command.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:45)
    at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
    ... 4 more
Caused by: liquibase.exception.DatabaseException: Expected single row from liquibase.statement.core.GetViewDefinitionStatement@1de5f259 but got 0
    at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:146)
    at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:157)
    at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:152)
    at liquibase.database.AbstractJdbcDatabase.getViewDefinition(AbstractJdbcDatabase.java:892)
    at liquibase.snapshot.jvm.ViewSnapshotGenerator.snapshotObject(ViewSnapshotGenerator.java:78)
    ... 22 more
Caused by: liquibase.exception.DatabaseException: Empty result set, expected one row
    at liquibase.util.JdbcUtils.requiredSingleResult(JdbcUtils.java:141)
    at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:144)
    ... 26 more
For more information, use the --logLevel flag

**Comment by MarkWojciechowicz** [comment]
Sorry - this issue should have been posted to Jira - I will put it there
